# Generated by Django 4.2.4 on 2023-10-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auto_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano', models.IntegerField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_auto_category', to='App.auto_category')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('Valor_Servico', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('data_nasc', models.DateField()),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('data_nasc', models.DateField()),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price_total', models.IntegerField(blank=True, max_length=200, null=True)),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Requester', to='App.clientes')),
                ('Service_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_Service', to='App.categoria_servico')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('qt_Stock', models.IntegerField(max_length=250)),
                ('producer_name', models.CharField(max_length=200)),
                ('producer_code', models.CharField(max_length=200)),
                ('Buy_price', models.IntegerField(max_length=200)),
                ('Sell_price', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.CharField(max_length=200)),
                ('discount_value', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Valor_Final', models.IntegerField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Category', to='App.payment_category')),
                ('manutention_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manutencion', to='App.manutencion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Status', to='App.payment_status')),
            ],
        ),
        migrations.AddField(
            model_name='manutencion',
            name='Used_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Used_Products', to='App.produtos_manutencao'),
        ),
        migrations.AddField(
            model_name='manutencion',
            name='dados_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dados_Auto', to='App.auto_register'),
        ),
        migrations.AddField(
            model_name='manutencion',
            name='funcionario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Relized_Employee', to='App.funcionarios'),
        ),
    ]
