# Generated by Django 4.2.4 on 2023-10-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_register',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categoria_servico',
            name='Valor_Servico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manutencion',
            name='Price_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Valor_Final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos_manutencao',
            name='Buy_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtos_manutencao',
            name='Sell_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtos_manutencao',
            name='qt_Stock',
            field=models.IntegerField(),
        ),
    ]
