# Generated by Django 4.2.4 on 2023-10-05 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_alter_auto_register_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_category',
            name='type',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Trem', 'Trem'), ('Caminhão', 'Caminhão')], max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria_servico',
            name='tipo',
            field=models.CharField(choices=[('Troca de Oleo', 'Troca de Oleo'), ('Troca de Velas', 'Troca de Velas'), ('Rodizio Pneus', 'Rodizio Pneus'), ('Troca Farol', 'Troca Farol')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='manutencion',
            name='Service_Category',
        ),
        migrations.RemoveField(
            model_name='manutencion',
            name='Used_Product',
        ),
        migrations.AlterField(
            model_name='payment_category',
            name='Payment_type',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão Credito', 'Cartão Credito'), ('Cartão Debito', 'Cartão Debito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FUNCIONARIO', 'FUNCIONARIO'), ('CLIENTE', 'CLIENTE')], max_length=200)),
                ('data_nasc', models.DateField()),
                ('cpf', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='manutencion',
            name='Cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Requester', to='App.customuser'),
        ),
        migrations.AddField(
            model_name='manutencion',
            name='Service_Category',
            field=models.ManyToManyField(related_name='Category_Service', to='App.categoria_servico'),
        ),
        migrations.AddField(
            model_name='manutencion',
            name='Used_Product',
            field=models.ManyToManyField(related_name='Used_Products', to='App.produtos_manutencao'),
        ),
        migrations.AlterField(
            model_name='manutencion',
            name='funcionario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Relized_Employee', to='App.customuser'),
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
