# Generated by Django 4.2.4 on 2023-10-12 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_reserva_manutencion_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
