# Generated by Django 4.2.4 on 2023-10-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_reserva_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='data_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='oficina_3_disponivel',
        ),
    ]
